### ISSUE TITLE
CT compressionFunction is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#105]
```
isotopes-and-atomic-mass : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637683103029%22%2C%22timestamp%22%3A1637685063677%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: compressionFunction is not a function
TypeError: compressionFunction is not a function
at reduceRadiusRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/shred/js/view/IsotopeElectronCloudView.js:111:20)
at IsotopeElectronCloudView.getElectronShellDiameter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/shred/js/view/IsotopeElectronCloudView.js:114:20)
at updateNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/shred/js/view/IsotopeElectronCloudView.js:41:73)
at new IsotopeElectronCloudView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/shred/js/view/IsotopeElectronCloudView.js:49:9)
at new IsotopeAtomNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/isotopes-and-atomic-mass/js/make-isotopes/view/IsotopeAtomNode.js:27:38)
at new InteractiveIsotopeNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js:40:33)
at new MakeIsotopesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/isotopes-and-atomic-mass/js/make-isotopes/view/MakeIsotopesScreenView.js:73:35)
at MakeIsotopesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/isotopes-and-atomic-mass/js/make-isotopes/MakeIsotopesScreen.js:29:55)
at MakeIsotopesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Screen.js:206:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Sim.js:609:24)
id: Bayes Chrome
Snapshot from 11/23/2021, 8:58:23 AM
```

**Comment by jbphet** [comment]
The problem does not seem to be occurring anymore, here is a screenshot of the latest CT data:

![image](https://user-images.githubusercontent.com/3082831/143930791-e570668e-642a-429f-a95e-9eec49073951.png)

The problem looks like it was actually happening in joist, and some work was being done there for TypeScript support, so I'm going to chalk this failure up to that activity and close.
