### ISSUE TITLE
CT Cannot set properties of undefined (setting 'fill')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#109]
```
isotopes-and-atomic-mass : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at am.setHighlighted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1702113)
at n (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1703687)
at g.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:16852)
at new cm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1703730)
at new gm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1704219)
at new Dg (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1765808)
at Lg.name [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1767610)
at Lg.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1222044)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1494784)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832732921%7D&fuzz&memoryLimit=1000:967:1494927)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at am.setHighlighted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1702113)
at n (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1703687)
at g.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:16852)
at new cm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1703730)
at new gm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1704219)
at new Dg (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1765808)
at Lg.name [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1767610)
at Lg.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1222044)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1494784)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/build/phet/isotopes-and-atomic-mass_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836139506%7D&fuzz&memoryLimit=1000:967:1494927)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667829332526%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667837117980%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667834782143%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667829378638%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836242920%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667830717854%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667838088103%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667832648917%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

isotopes-and-atomic-mass : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667837019047%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot set properties of undefined (setting 'fill')
TypeError: Cannot set properties of undefined (setting 'fill')
at (PeriodicTableCell.js:96:23)
at setHighlighted (PeriodicTableNode.js:104:24)
at listener (ReadOnlyProperty.ts:407:4)
at link (PeriodicTableNode.js:107:35)
at (ExpandedPeriodicTableNode.js:48:30)
at (MakeIsotopesScreenView.js:94:30)
at (MakeIsotopesScreen.js:37:15)
at createView (Screen.ts:298:22)
at initializeView (Sim.ts:877:15)
at (Sim.ts:885:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM
```

**Comment by jbphet** [comment]
@Luisav1 - This CT failure looks like it was caused by some commits that you made recently.  There are some options to the constructor for `PeriodicTableCell` that control whether the `labelText` field is present, and it looks like your code is assuming that this field is always there.  Please have a look, and let me know if you'd like any help with it.

Assigning to @Luisav1 for follow-up, and also to @chrisklus since he's working on this as well.
