### ISSUE TITLE
CT failing due to a new test for acceptable max width values

### ISSUE THREAD

**Issue by jbphet** [phetsims/isotopes-and-atomic-mass#84]
This sim is failing continuous test, readout shown below.  It is happening due to a bounds check that was recently added to test for valid maxWidth values in scenery nodes.

CT error output:

```
isotopes-and-atomic-mass : fuzz : require.js : load
Uncaught Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/assert/js/assert.js:22:13)
    at Text.setMaxWidth (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539105162497:2461:17)
    at Text.set maxWidth [as maxWidth] (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539105162497:2473:34)
    at updateElementName (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539105162497:196:28)
    at Emitter.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539105162497:245:7)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539105162497:201:53)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/model/MakeIsotopesModel.js?bust=1539105162497:87:31)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539105162497:246:52)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:271:29)
    at DerivedProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:252:14)
Approximately 10/9/2018, 10:21:14 AM
isotopes-and-atomic-mass : fuzz : require.js : load
Uncaught Error: Assertion failed: reentry detected, value=0, oldValue=1
Error: Assertion failed: reentry detected, value=0, oldValue=1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:268:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:252:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:195:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/NumberProperty.js?bust=1539105162497:86:30)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/ObservableArray.js?bust=1539105162497:200:29)
    at ParticleAtom.removeParticle (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/shred/js/model/ParticleAtom.js?bust=1539105162497:387:22)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/shred/js/model/ParticleAtom.js?bust=1539105162497:449:57
    at Array.forEach (<anonymous>)
    at ObservableArray.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/ObservableArray.js?bust=1539105162497:307:27)
Approximately 10/9/2018, 10:21:14 AM
isotopes-and-atomic-mass : fuzz : require.js : run
Uncaught Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/assert/js/assert.js:22:13)
    at Text.setMaxWidth (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539105162497:2461:17)
    at Text.set maxWidth [as maxWidth] (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539105162497:2473:34)
    at updateElementName (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539105162497:196:28)
    at Emitter.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539105162497:245:7)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539105162497:201:53)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/model/MakeIsotopesModel.js?bust=1539105162497:87:31)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539105162497:246:52)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:271:29)
    at DerivedProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:252:14)
Approximately 10/9/2018, 10:21:14 AM
isotopes-and-atomic-mass : fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0, oldValue=1
Error: Assertion failed: reentry detected, value=0, oldValue=1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:268:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:252:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539105162497:195:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/NumberProperty.js?bust=1539105162497:86:30)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/ObservableArray.js?bust=1539105162497:200:29)
    at ParticleAtom.removeParticle (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/shred/js/model/ParticleAtom.js?bust=1539105162497:387:22)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/shred/js/model/ParticleAtom.js?bust=1539105162497:449:57
    at Array.forEach (<anonymous>)
    at ObservableArray.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/ObservableArray.js?bust=1539105162497:307:27)
Approximately 10/9/2018, 10:21:14 AM
isotopes-and-atomic-mass : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
Error: Assertion failed: maxWidth should be null (no constraint) or a positive number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/assert/js/assert.js:22:13)
    at Text.setMaxWidth (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539104626721:2461:17)
    at Text.set maxWidth [as maxWidth] (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/scenery/js/nodes/Node.js?bust=1539104626721:2473:34)
    at updateElementName (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539104626721:196:28)
    at Emitter.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/view/InteractiveIsotopeNode.js?bust=1539104626721:245:7)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539104626721:201:53)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/isotopes-and-atomic-mass/js/make-isotopes/model/MakeIsotopesModel.js?bust=1539104626721:87:31)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Emitter.js?bust=1539104626721:246:52)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539104626721:271:29)
    at DerivedProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539102074775/axon/js/Property.js?bust=1539104626721:252:14)
Approximately 10/9/2018, 10:21:14 AM
```

**Comment by jbphet** [comment]
Should now be fixed, I'll take a look at CT in about two hours from now and, if the tests are passing, I'll close.

**Comment by jbphet** [comment]
All tests have succeeded for this sim for the last four rounds of CT, closing.
